* IMP-X4 シミュレータ 高速化要求
** 高速化要望 (5/12萩様)
  実行速度に問題があって、なかなか移行が進みません。
  SoftVPより遅いです…。

  1. IMRが、1プロセスのみとなっていて、実行待ちが多い
    →複数のプロセスで実行できませんか？

  2. IMP関連のAPIを高速化して欲しい。
    →例えば、OpenCLを使う等…。効果の大きいものだけなど限定的な適用でもOKです。
** 高速化回答 (5/12鵜飼さん)
  高速化に関しては引き続き改良を行っていますが、今回のSimのコンセプト上、
  SoftVPの速度には到達できません。（前回訪問時に説明済）

  1. IMRの複数のプロセス実行
    → 検討含め対応に2，3か月を要します。
       Final版リリース後開始したと仮定すると8月以降となります。
       対応するためには詳細な条件を頂きたいと思います。
            例：IMR-LX 、 IMR-LSXどちらを利用するのかなど

  2. IMP関連のAPIを高速化して欲しい。（例えば、OpenCL）
    常に高速化は作業を行っており、現在のversionはα版（12月）に対してAPI全体的に
    40%程処理時間の削減（＝高速化）を実現できています。
    引き続き高速化は行っていますが、α版に対して50%程が目標値となりえると思います。
     （＝SoftVPと同じ処理時間には本Simのコンセプト上なり得ません）

    尚、OpenCLでの高速化は多くの工数を要するために、対応は困難です。
    どの版（α版？β版？）を利用されていますでしょうか？
    Final版での動作をみてからご判断いただくことはできないでしょうか？

  - 実行速度が遅く移行が進まないとのことですが、今回のSimコンセプト上  困難な課題です。
    まずはFinal版を見て頂くとしても、最終的にこれが原因で全く移行できないということであれば
    Implibに限ってはコンセプトを再変更するしか手段がないと思われます。
    尚、CVLibに関してはSoft版を用意しており、HW Emulateを行わずに処理を行うモードを用意しており
    処理速度に大きな問題はないと思われます。

** IMRSim改善検討 (5/18打合せ)
  - [X] 5/20 SoftVP拡張ライブラリのIMR Sim改善日程感回答
  - [X] 6/05 ← 5/末 IMP-X4 Sim Final版リリース
  - [X] 5.29 IMR Sim対策版リリース
    1. コンパイルオプションの見直し
    2. プログラム構造の見直し
** 高速化第二弾検討
  - [X] 5/25 IMRの内部の処理をマルチスレッド化の検討結果回答


