* 2015年度クラリオン中国購買方針説明会
首記の件、中国クラリオン購買方針説明会の内容を
以下に纏めましたので、内容ご確認お願い致します。
大川M、修正追記御願い致します。

---
日時：2015年3月27日(金)14:00～16:00
場所：東坑鎮中凱国際酒店国際宴会庁(DCOE近くのホテル)
出席：REHK/小笠原様・RECHK/大川M・岡崎記
内容：
 1、新組織体制及び経営方針      DCOE/川島社長
 2、2015年度購買方針            本社購買/山田本部長
 3、中国購買・調達活動報告      DCOE中国購買調達本部/菊池本部長
 4、CXEE R&Dプレゼンテーション  CXEE/今井副総経理
 5、品質方針・品質活動報告      DCOE中国品質保証本部/小林本部長
 6、2014年度優秀取引先表彰      DCOE/川島社長

■所感
環境の変化激しい中国市場で、注力しているP/Fでのコストダウンが必要となっており、
更なる変革と競合他社からの勝ち残りが必要である。
CXEEでの設計土台が出来上がりつつあるものの、低コスト品調達の流れ強く、
為替リスク対策として日本移管案件が増えていく感がある。
しかし、日系・ローカル関わらず競争力のある製品の積極採用を促進しているため、
REL品と共にCSB製品の更なる探索と拡販により、実を結ぶ可能性があると感じた。
また、日頃の日本関係者様からのご協力もあり、優良サプライヤー賞を頂きました。
(品質と納期遵守率/150社中6社、日系はRECHKと村田)この場をお借りし御礼申し上げます。

■新組織体制及び経営方針
(1)中国体制

CHI：
 村上会長(新任)
 宮元社長

DCOE：
 川島董事長(新任)
 熊坂社長(新任)
 鄧副社長
 斎藤副社長(新任)

CXEE：
 對馬董事長(新任)
 植野総経理
 今井副総経理

(2)業績見込(2015年/3月期)※億円未満四捨五入/()内計画
 売上高：1,975(2,000)
 営業利益：53(70)
 経常利益：41(63)
 当期純利益：24(47)
 ※開発費等がかさみ、計画に対してマイナス。

(3)2020年への経営方針(車両情報システムプロバイダーとしてグローバルに成長)
 ①「安心・安全」「コネクティビティ」「基盤」事業の強化
 ②グローバル開発マネジメント(CXEE開発移管の加速)
 ③品質の総点検(成長分野を支える製造品質)

(4)中期戦略(中国のMission)
 ①PRC事業→売上拡大
  ・顧客戦略・・・外資系顧客4社と中国系顧客への重点活動
  ・商品戦略・・・Paxi3(AVN/DA)導入による市場要求への対応

 ②生産事業→競争力強化に向けた改革
  ・原価低減・・・最適地購買、重点機種原価管理
  ・自動化、工法改革、トレーサビリティ強化

 ③R&D事業→自立から主体へ
  ・PRC売上に貢献する承認開発及グローバル機種開発の全移管
  ・開発品質向上・・・発生不具合抑止及び流出不具合抑止

(5)生産計画推移(工場別/2014年～2017年にかけて)
 CMS：ディスプレイオーディオ・ナビカメラ等 増加
 CAT：ASEAN・インド市場向けディスプレイオーディオ・ナビ・カメラ等 増加
 CM ：横ばい
 CXEE：横ばい
 DCOE：中国向けナビ・カメラ等増加
 CHE：緩やかな右肩上がり
 ELECLA：緩やかな右肩上がり

■2015年度購買方針
 6つのキーワード：
  事業ポートフォリオの変革、販売価格の下落、為替変動への追従、
  地産地消への対応、サプライヤーマネジメント強化、調達ロスコストの削減

(1)購買方針
 ・日系・ローカル問わず、コスト比較により競争力ある部品の採用
 ・フレキシブルな為替リスク対策実施
  15年度の日本国内生産向け購入を拡大する計画あり
  (N社向けHDDナビゲーション、15MYナビゲーション、
  H社向けディスプレイオーディオ、M社向けカメラ等)
 ・グローバル・ワン・バイヤーの深化
 ・CHI(IPO)調達から現地調達化促進(タイ、メキシコ、ハンガリー)
 ・コスト造成
  VEC提案、適正品質部品提案、生産拠点周辺のLCC部品の情報開示の御願い

(2)設計購買連携&日中連携活動
 ①2014年度状況
  CXEE：日本証券のAUDIO完全移管、AV NAVI部分移管。
     PRC商権における新規NAVI PFの自主開発開始。
  日本設計：インテリジェントセーフティ機器開発への移行。

 ②2015年度計画
  日本のVEC推進PJと中国のPRC VEC PJとの情報共有化の推進。
  高額部品をターゲットにした日中連携ソーシング活動強化。
  中期開発におけるインテリジェントセーフティ機器必要部品の設計購買連携調査。

■中国購買・調達活動報告
(1)購買体制強化活動
 ・ソーシング体制の強化・購買部の強化・部品メーカー評価基準の改善

(2)原価低減強化活動
 ・開発初期段階でのLCC部品採用検討
 ・地産地消の徹底
  為替の状況に応じ、現地⇔日本調達の適宜切り替えの実施
  15年度は円安継続により日本調達比率が増える見通し
 ・VEC活動の強化

(3)お客様との共同活動
 ・調達保全・金型管理の徹底・キャッシュフロー改善強化・外注管理強化
 ・グリーン調達の推進

(4)調達システム改善活動
 ・納入遵守率向上・納入管理の強化・T-SCM改善活動実行(納品バーコード化推進)

■CXEE R&Dプレゼンテーション
(1)開発体制強化
 ・CXEE開発強化
  2010年：180人→(要因の増加)→2014年：650人
  2015年：680人／2016年720人
  ※要因の量から質への転換(質向上・能力UP・生産性向上)

(2)商品戦略
 PRC状況：
  既存の日系、外資系に加え民族系を延ばす。
  コア事業(Navi/Audio)が引き続き中心。ISの商権拡大が課題。

 Navi/Audio：
  今までのPaxi3活動：Paxi3/ARCUS Navi/DA(Paxi2コストで付加価値)
  Paxi3 30%コストダウン活動モデルを基準とし、その活動成果を
  今後の商権獲得・収益改善活動に繋げる。

(3)中国IVIトレンド
 以下中国市場でトレンドとなるインフラ機能郡。
 ①Navigation
  ・北斗衛星(中国版GPS) ・クラウド型音声検索 ・スマートフォンナビ
  ・iOS in the car
 ②Security＆Safety
  ・画像認識(センシング) ・駐車アシスト
 ③Communication
  ・TD-LTE(4G) ・WiFi ・3G,4G通信モジュール(TCU) ・スマートフォン連携
 ④Entertainment
  ・スマートフォン連携

■品質方針・品質活動報告
(1)14年度は、生産数がGr内約半数のDCOEの品質悪化により、
 全社品質に悪影響を与えた。(CL全社：30PPM、DCOE：27PPM)
 昨年に引き続き、以下管理レベルの向上を行う。

 ・4M変更管理の徹底
 ・多層基板TH問題の撲滅
 ・再発防止、水平展開の徹底
 ・金型の更新管理
 ・新規部品に対する部品認定

(2)サプライヤのスコア評価
 15年度よりDCOEにて品質スコア評価施行。
 16年度より正式運用。(持点100点から品質問題発生の都度減点。)



