* AVM高速化対応 GHSオンサイトサポート 進捗連絡会 4/20～4/22
** AVM高速化対応 進捗連絡会 <2015-04-20 月>@ 18:00-20:00 at 電話会議
*** 電話会議
   - WebEx：
     https://hitachi-ad.webex.com/hitachi-ad/j.php?MTID=mb11a30484909da0b5a799d9bed701213
     ミーティング番号: 861 395 802
     ミーティングパスワード: clarion　
   - 電話会議：
     日立電話会議システム使用(内)8022
     (外)0120-914803 もしくは 03-4503-6121
     カンファレンスコード： 6527811611
*** 参加者
    in 戸塚
     CL/吉岡、加藤
     GHS/Scott
     REC/藤巻
     ADaC/工藤、慶野、鈴木、福富
     HiICS/川上、佐藤
    CL/岩田、高田
    REL/大橋、小林
    REC/高草
*** 現状 usleep対策版での評価
   静止立体物検知：250-300msec
   移動体検知：400-500msec
   駐車枠認識：400msec
*** オンサイトでの確認事項
   1. M6.3移行確認
     → M6.3にHiICSでの変更差分を反映し、Scottとソースレビュー
        変更に問題が無いことを確認した。
     → 実機での動作（画面表示）は問題ないが、リプロ動作が途中で
        停止する問題があるため、検証が必要。Kernel Panicの発生は無い。
   2. デバッグ版カーネル組込
     割込みハンドラ、Callback、IODevice全関数のStart/Endにイベントアナライザ用の
     イベントを追加したデバッグ専用カーネルライブラリを提供した。（GHS）
     → イベントログ上は割り込みと同じアイコンで見える。
        ISRの開始：Interrupt(types=0x2/0x1d pc=0x4xxxxxxx)
        ISRの終了：Interrupt(types=0x2/0x1d pc=0x1)
        コールバック：Interrupt(types=0x2/0x1001 pc=0x4xxxxxxx)

     イベントログ（.merファイル）をgdumpを使ってテキストファイルに変換できる。
     集計するためのPythonスクリプトを提供した。（GHS）

     → usleepリプロ時の問題を解析しようと試みたが、イベントログをダンプする際に
        "invalid event type via rtserv2 : 0x0"のエラーでイベントアナライザが開かない。
        GHSのエンジニアに確認する。（GHS）
   3. デバッグ版カーネル実行結果解析
     - デジ収装置を接続して、パフォーマンス解析のためのログを収集。
       フラッシュROMからMonolithをブートし、ランモード接続__INTEGRITY_DebugEventLogSize
       を 8MB（0x800000）に変更してイベントアナライザでログを取得。
      → 正常にログが収集できることを確認した。
     - リリース版（no libdebug, kernel_opt）での表示結果確認
      → デバッグ版と比べ、100msくらい速くなっている。
     - VIEW_TASKの負荷解析について
      VIMainのforループ1回の処理時間が4～5msの処理に対し、2～3msで更新要求がはいっている
      2DGの頻度を下げられないか？
     → まとめて処理すべきでは？
     → UserEventを挿入してイベントログをとって解析する（HiICS）
   4. 解析結果反映後の対策実施
   5. GHS質問票の課題確認
    1. TimeWaitForSemaphoreの動作について
    2. 起動シーケンスについて
    3. KernelドライバのCPU動作についてV2Hの仕様確認
    4. 割り込みイベント通知について
    5. LateKernelRangeClear機能について
    6. EarlyKernelRangeSize
    7. カーネルメモリ不足時の動作について
    8. CPU一つが死んだ時の動作について
    9. トラップできるエラーについて
    10. コンパイルオプションの適切な設定について
    11. イベントログのアイコンについて
    12. R-CarV2Hの
*** ViewTask処理負荷解析報告 (REL)
   while文を使用し、複数コマンドを纏めて実行
   → 効果ありそうだと判断 (吉岡様、加藤様)
   → お試し版評価を4月中に行う
   ViewTaskで一回4-5msecかかっているのが適切かどうかに拘っている (萩様)
*** DONE H/Wとしての画認処理時間の理想値 (SH7766の時に出してる？)
    CLOSED: [2015-04-27 月 14:37]
** AVM高速化対応 進捗連絡会 <2015-04-21 火>@ 18:00-20:00 at 電話会議
*** 電話会議
   - WebEx：
     https://hitachi-ad.webex.com/hitachi-ad/j.php?MTID=m3af849a9bd0cbd3d170cdc73b5b200e8
     ミーティング番号: 866 805 820
     ミーティングパスワード: clarion 
   - 電話会議：
     日立電話会議システム使用(内)8022
     (外)0120-914803 もしくは 03-4503-6121
     カンファレンスコード： 6527811611
*** 参加者
   in戸塚
     CL/吉岡、加藤
     GHS/Scott
     REC/藤巻
     ADaC/慶野、鈴木、福富
     HiICS/川上、佐藤
   CL/岩田様、塩屋様、高田様、萩様
   REL/大橋さん、星さん、木村さん
   REC/高草
*** パフォーマンス解析報告
   - Owholeprogram試行
    → BSP多重定義でBuildエラー
    → 画認アプリ限定で -Ospeed オプション適用
   - GetTaskIdentificationの呼び出し時にKernelCallせずにOSラッパ内のテーブル検索に変更
   - 画認アプリ処理時間
    PLR: 118ms max.   83ms ave.
    SMP: 116ms max.   44ms ave.  ※SMP= 空間マップ
    SOD: 121ms max.   52ms ave.  ※Min.0のケースあり
    MOD: 237ms max.  193ms ave.  ※CPU(差分計算)で処理。IMP使用で高速化の余地あり
     全体的に20～50ms程度高速化
    → イベントトレース追加カーネルにて検証、ログ解析中。
*** RELへの質問
   - ASP_FlushCacheesの処理について期待値通りか？ (スコットさん)
    → 期待通りです (木村さん)
    → DisplayList連結のアドバイスで回数は減らせると思います (星さん)
*** MOD処理のIMP処理化
   Circleで差分を出しているところをIMP化
   - [ ] サンプル4/24(金)リリース (木村さん)
*** PLR(ImageDirect)のIMP処理化
   状況確認後、定例にて報告する (加藤さん)
*** DDRのメモリ配置 (REL/木村さん)
    一次試作：MT41K256M16HA-125
    Configurationが、以下の3つあります。
    (1）1 Gig × 4 1G4 1KByte
    (2）512 Meg × 8 512M8 1KByte
    (3)256 Meg × 16 256M16 2KByte

    それぞれページサイズが
    (1)、(2)は1KByte、(3)は2KByteとなり、バンク数は
    全て8ですので、それぞれ、8KByte、8KByte、16KByte毎に
    バンクが一巡します。

    (1)、(2)については、YとUVプレーンの先頭アドレスの
    8KByte未満が4KByteずれていることが、連続するY、UV
    プレーンアクセスが互いにDRAMの同一バンクでのページミスを
    起こさないマッピングになります。

    (3)では、16KByte毎に一巡ですので、16KByte未満のアドレスが
    8KByteずれていることになります。

    二次試作：IS46TR16128B-125KBLA1
    についても
    256M × 8 1KByte
    128M × 16 2KByte
    で、バンク数も8ですので、一次試作のものと同じになります。

** AVM高速化対応 進捗連絡会 <2015-04-22 水>@ 18:00-20:00 at 電話会議
*** 電話会議
   - WebEx：
     https://hitachi-ad.webex.com/hitachi-ad/j.php?MTID=m0890d47a99091a2a58d6b4e4afd5eae6
     ミーティング番号: 866 264 464
     ミーティングパスワード: clarion 
   - 電話会議：
     日立電話会議システム使用(内)8022
     (外)0120-914803 もしくは 03-4503-6121
     カンファレンスコード： 6527811611
*** 参加者
   in戸塚
     CL/吉岡、加藤
     GHS/Scott
     REC/藤巻
     ADaC/慶野、鈴木、福富
     HiICS/川上、佐藤
   CL/岩田様、塩屋様、高田様、萩様
   REL/大橋さん、木村さん、星さん
   REC/高草
*** 進捗確認
**** HiICS/川上様
    - シリアルリプロのfail → HiICSで継続調査
    - GHS質問表16件 → ひと通り確認完了も宿題事項もあり。別途更新版展開
     - 機能安全周りでGHS-CLのNDA締結が必要 → CL/岩田様
     - メールサポート。ADaC・GHSにパラで展開
**** CL/加藤様
    - 画認パフォーマンスについてイベントログ解析実施 → 課題箇所が見えてきた
      IMP: 150msec/1.7sec 割り込み3000回 ← fbioのwriteStatusが多い
      SPI: 13msec/1.7sec 割り込み1000回 → 差分通信に変更
      GPIO: 1msec/1.7sec 割り込み3000回 → MemoryRegionに変更(但し効果大ならば)
**** REL/木村さん
    - DisplayList
      libに問題が残っている為、リリース遅れます → リリース日程は後日回答
    - 横切り検知の木村さん対策版をリリース → 4/23中
     → 割り込み回数がどれだけ削減出来ているか確認してもらう → CL
    - HomologyCircle
     累積値を作るところまでIMPで対応出来そう
     IMRを使った方が早いかもしれない → CL/加藤様確認
**** vi_task
    - アイコンの読み出し 2.64msec x 11個 のウェイトが大きい
     → HiICSで処理方法の見直しを行う

*** 確認事項
   - M6.3中国版パッケージの準備 → GHS
   - サンプルアプリの中国展開OKか？ → REL: 中国版PKGでビルド可能なものであれば提供可

*** GHSからのAdvice
   1. 性能評価の際には性能測定用の環境にて測定すること
   2. 同期のために優先度変更しているが、使わないように。
   3. Kernel APIの呼び出しを可能な限り削除するように
   4. SemaphoreよりLocalMutexを使うべき
   5. fbioDevWritesStatus、SPIの割り込みパンドラ、GPIOのWriteStatusの読み出し頻度改善
   6. 解析手法
    - 関数ごとにどの関数が多く呼び出されているか: Profiler
    - どのタスクに時間がかかっているか: Profiler or ResourceAnalyzer
    - タスクの中身: EventAnalyzer
    - 詳しい測定、割り込みパンドラ、Callbask: EventAnalyzer + gdump
   7. KernelCallを行うAPI一覧をADaCから提示

*** 宿題事項
**** ユーザアプリ側でのIMPコア予約
**** Display List活用
**** Local Memoryの活用のガイド いつまでに何をやるか

* IODEVICE / 画像認識 高速化：進捗連絡会 <2015-04-27 月>@ 18:00-20:00  at 電話会議
** 電話会議システム
  外線アクセス番号：03-4503-6121, 0120-914803
  カンファレンスCD：1773317928
  https://hitachi-web-conference.webex.com/hitachi-web-conference/j.php?MTID=mdd3557287b07bc00c275a6dfd2f859fd
  ミーティングパスワード: 1234
** 参加者
  CL/吉岡様、高田様、加藤様、萩様
  HiICS/川上様、佐藤様、納富様
  ADaC/慶野さん、工藤さん、福富さん、清水さん
  REL/星さん、木村さん、大塚さん
  REC/高草、藤巻
** 進捗確認
  1. No.05 長期レンジでの高速化アドバイス
     - IMP予約：CL環境でメモリ確保でエラーが発生してしまう
               → VaRecog部分を参照して欲しい → 参照部分を後ほど加藤様より連絡頂く
       - [X] 下記BSRを再優先とし、若しくは使い方の説明を5/07リリース。5/08暫定版リリース。
     - HomologyCircleのIMP処理化：REL環境では動く。加藤様は正常に動いておらず。
               → 制約事項等あるか？ → 特にないが、
       - [X] 4/28にCL環境で確認を行う。
  2. No.10 IODeviceNotify
     - 再度ADaCで再現確認を行う
  3. No.13 DMAC使用
     - [X]資料更新して提出します。提出日を4/28回答 → 5/07提出
** 日産への回答
  - 4/27 岩田さんが日産へ訪問。
  - 5/12 日産内でデモ実施予定。
  - マネージャ層までの参加。


