* IODEVICE / 画像認識 高速化：進捗連絡会 <2015-04-06 月>@ 18:00-19:00 at 電話会議
** CT-WEBEX
    ミーティング番号: 869 443 230
    ミーティングパスワード: 1234
    1. https://hitachi-web-conference.webex.com/hitachi-web-conference/j.php?MTID=mc6ba63f063ce2cc90946cb171ca1fb3f へ進む。
    2. 必要に応じて名前とメールアドレスを入力してください。
    3. パスワードが必要な場合は、次のミーティングパスワードを入力してください: 1234
    4. [参加] をクリックします。
** 電話会議システム
    外線アクセス番号：日本：03-4503-6121	0120-914803
    カンファレンスCD：1773317928

** 出席
   CL/萩、高田、岩田、緒方、吉岡、加藤、
   REL/大橋、星、小林
   REC/高草、藤巻
   HiICS/川上、佐藤、斉藤
   ADaC/慶野、工藤、福富、清水

** クラリオン状況
   4/08(水)に日産に対して高速化状況の説明を行う。
   静止物体の処理時間要求100mmsecに対し、現行300mmsec
   4/07(火) にREL-CLで画認アプリのアルゴリズム説明の打合せ実施

** 課題管理表
 1. No.05 長期レンジでのパフォーマンス改善
   4/07(火) にアルゴリズム説明会開催

 2. No.06 MSIOFデータジスタアクセス時間
    - [ ] 4/10 No.06 ハード仕様でいいのかということをハード部門へ確認し回答する

 3. No.08 DLL化対応検討
   No08_DLL_Problem_20150403.pdf で回答済
    - LoadModuleを使用してみる価値がある - HiICS/佐藤様

 4. No.09 usleepについて
   No09_usleep_Latency_20150403.pdf で回答済
   継続調査・解析を行う
    - [ ] No.09 具体的な作業日程の回答を別途RELと打合せ後回答する

 5. No.10 IODeviceNortifyについて
   No10_IODeviceNotify_Latency_20150403.pdf で回答済
   継続調査・解析を行う
    - [ ] No.10 具体的な作業日程の回答を別途回答する

 6. No.11 カーネルコール時間の短縮改善
   KernelCall_Performance_20150403.pdf で提案済
   デバッグライブラリの削除によって、画認アプリは30%以上速度向上した。
   量産版についてはデバッグライブラリ削除するが、それは最後の手段。
  ⇒ クローズ

 7. No.12 MSIOF処理時間短縮
    - [ ] 4/10 No.12 DMAC仕様の回答。DMAC使用時の転送速度期待値の回答

 8. No.14 Vin周りの高速化
   メモリドライバ改善をView側でも確認する
   CPU負荷が高そうなものは他にあるか ＞ 大きいものは特にないですね - 大橋

 9. No.15 ディスプレイリスト作成の高速化
   2DGで直接Flashにアクセス出来ない
   デジタルアイコンになってメモリ上に全て読み込めない。画面遷移があった時にFlashから読み込む
   - [ ] 4/13週 No.15 問題箇所の分析・抽出 ＞ HiICS

** コンパイラオプションによる向上
*** VFPU V3にしてみた (NEONオプションも同時にオンになる- 慶野) - 大橋
   MOD 3%向上
   SOD 1.5%向上
*** NEON -oI -oB -omax
   VFPU程効果は見込めなかった
*** CPU指定でデフォルトvfpuv3になるはず
    - [X] コンパイラオプションCPU指定でvfpuv3がオンになるか確認 ＞ 慶野

** DRAM メモリマップによる向上は可能か
  SH7766の時やったやつ - 岩田
   Re: クラリオン：【質問】SH7766での映像表示不具合について
   2013/10/16 from:Hiroyuki.Hamasaki
*** 当時のメール
大変遅くなりましたが、クラリオン殿から提供いただいたＤＬ
でのシミュレーション結果がでましたので連絡いたします。

シミュレーション結果　ーーーーーーーーーーーーーーーーーーー
●クラリオンＤＬ
DSOR=0xC8000 224.9us
　（4チャネル全てが終了した時の実行時間）

●ＤＳＯＲを変更した場合
DSOR=0xC9000 112.1us　
　（4チャネル全てが終了した時の実行時間）
　処理時間が、半分以下になりました。
ーーーーーーーーーーーーーーーーーーーーーーーーーーーーーー

クラリオン殿でのＹプレーンとＵＶプレーンが16KBの整数倍の
オフセットとなるメモリ確保での処理時間は、
４ラインの取り込み時間を 254usとすると、IMR-LSXだけで
４ラインの取り込み時間の　96% となり、ぎりぎりです。
表示の複数プレーン表示等を考慮すると、描画の処理時間が間に
合わないということになります。

一方、ＹプレーンとＵＶプレーンが仮に、16KBの倍数＋
4KB(２バンク分)ずらした場合では、254usの44%となりました。

ＹプレーンとＵＶプレーンのメモリ確保により、常にＤＲＡＭ
のページミスを起こすような配置になると、本来使えるメモリ
の実行帯域のさらに半分も使えなくなってしまいます。
ＤＳＯＲの値だけで、今回の性能の差分がでていることからも
明らかなように、IMR-LSXの個々の性能で律速されているので
はなく、システムのメモリ効率による律速が原因と推測されます。

** GHS/スコット来日打合せ 4/16(木)
** 宿題事項
  - [ ] 4/10 No.6 レジスタアクセス時間:再確認結果の連絡>@RENESAS
  - [ ] No.8 V2Hの注意事項をドキュメント化してわかるようにして欲しい＞@ADaC
  - [ ] No.9,10 usleep,IODeviceNortifyディリーでの状況報告>@ADaC
  - [ ] 4/10 No.13 DMACでMSIOF利用の場合の確認>@RENESAS

** 次回進捗連絡会
  4/13(月) 18:00〜
  ClarionC-1:応接
