* CAT（クラリオン・タイ）のサプライヤーミーティング 2015/04/24
** ポイントは以下3点。
  - 生産を上げていく計画ではあるが足元は大変厳しい状況。市場の回復とNAVI、
    AVM（アラウンドビューモニタ）等ハイエンドモデルに期待。
  - 日立Gr一体となってソリューション提案が今後更に重要。
  - 為替対応として最適地購入の推進。（現調促進とは相反するのですが。。）

    CATとしてアセアン、中東、アフリカ市場をメインに販売強化していきたいが
    実態は北米向けを始めとしてW/Wへの輸出向けモデルに支えられている。
    当面はこの状況が続く見込み。
** <CAT 2015年 サプライヤーミーティング> 詳細
  日時：4月24日(金) 15:30～17:00
  場所：Centara Grand Mirage Beach Resort Pattaya Hotel
  出席者：サプライヤー56社 106名出席
  Clarion：和田取締役、山田購買本部長
  CAT：堀社長、細川副社長、野添担当副本部長、中原担当副本部長 他多数
  MC：KY Goh
  RESG：元山MD
  REC：渡部FG、西田EK
  RECTH：佐々木

** クラリオン事業方針説明（和田取締役）
*** 14年度振り返り
   14年実績 下記数値で着地予定。
   売上     ：1975億
   営業利益  ： 53億
   経常利益  ： 41億
   当期純利益： 24億

*** 環境の変化
   日本市場の回復低迷により海外への比重拡大
   スマホのデファクト化の価値観の相違
   メガサプライヤー主導によるプロセスの変更(センシング)
   自動運転の前倒し
   低価格化、共通ﾌﾟﾗｯﾄﾌｫｰﾑ化の加速
   2020年にはWW1億台→6,000万台がｺﾈｸﾃｨﾋﾞﾃｨｶｰ(IoT)へ
   内4,000万台はADAS対応。

*** 安全・安心な車社会貢献へ
   クラリオンとして車両情報システムプロバイダーを確立させる
   Intelligent, Safety, Connectivityの強化
   モジュール化の拡大と日立Gr（特に日立AMS）一体となりトータルシステム
   ソリューションの積極提案。
   新規BIZのスタート
   （服薬支援ロボ、システムバス向けフルデジタルサウンドシステム）

*** グローバル購買方針
   QCDDM（Quolity、Cost、Delivery、Development、Management）
   品目別購買戦略
   LCC部品の推進（地産地消）
   為替リスク対策
   品目別ワンバイヤー化促進

*** お願い事項
   価格と品質
   フレキシブルな為替対応（最適地購入の推進）
   ラインストップゼロ
   BCP策定

** タイ・アジア市場(アフリカ含む)について（堀社長）
*** 14年度＊900万台 15年度＊1000万台と先々伸張の見込み。
   市場規模
   2015年 = 790MUSD                       100%
    IS（Intelligent safety）                4%
    ITC（Intelligent Transport Systems）    2%
    Core(従来)                             94%

   2018年 = 1,000MUSD                     100%
      IS（Intelligent safety）              8%
      ITC（Intelligent Transport Systems） 11%
      Core(従来)                           81%

   各市場別 予測
   タイ  ：カメラ→AVM(Around View Monitor)、Cloud化
   インド：カメラ導入、ディスプレーオーディオ→ナビ化
   マレーシア：カメラ導入、ミラーリンク(携帯)
   インドネシア：ミラーリンク
   オーストラリア：Cloud化

   *急速にカメラの普及と画像合成、センシングを使ったADASが伸張

*** ICT市場
   ナビ→上位グレード機種を中心に増加
   ディスプレーオーディオ→ナビ化

** CAT状況と中期計画（細川副社長）
*** 2014年度状況
   15年3月で従業員は610名。生産ボリュームはCLGrで7％に過ぎない。
   日産ムラーノ向けナビ立上と１ﾗｲﾝ増設し、TOTOAL3ﾗｲﾝに増強完。

*** CAT生産キャパ
              /M     /Y
  オーディオ  61k    732k
  ナビ        22k    264k
  カメラ      15k    185k
  合計        98k  1,176k

*** 生産計画 （単位=k台）
             14年  15年  16年  17年
  オーディオ  410   481   508   482
  ナビ        126   218   245   240
  カメラ      171   236   502 1,024
  合計        707   935 1,255 1,746
  *2015年度は14年度比+24％を計画。
   2017年度にはカメラを主力に170万台を計画。
  *CL全体におけるCAT生産比率は14年:7%、15年:8%、16年：9%を予定

** CAT購買調達方針（野添担当副本部長）
  購入先を全世界フレキシブルに対応。→為替リスク回避＝最適地購入！

*** CAT調達金額実績及び見込み
        13年  14年  15年  16年
   THB  26億  29億  37億  49億
   JPY  91億 109億 138億 178億 ※\3.64/THB

*** 現調化促進
   アジア調達比率が増加。13年50%、 14年60%
   ただし、中国と比べ以前日本からの購入比率も高く余分な経費がかかっている
   一方では、為替に左右されない最適地購入の実践。。。

*** 原低方針
   - グローバルワンバイヤーの深化
   - VEC提案の推進 2015年目標 60件（14年実績15件）
     2件/サプライヤーの提示をお願いしたい

*** 納期遵守率
   14上：91.1%
   14下：92.5%      →15年目標 98%

*** WEB EDI導入の検討を開始

** QA方針（中原担当副本部長）
*** 部品に起因する故障率
   13年     8.6PPM
   14年     4.5PPM
   15年計画 4.0PPM以下

*** 15年目標
   重大クレームゼロ
   不良PPM4.0ppm以下
   市場クレーム3件以下

*** 活動方針
   サプライヤーのランク付け
   設計変更、工程評価の強化
   5段階評価の設定
   品質活動説明会の開催（9月頃開催予定 積極参加求む）

*** 2014年サプライヤー表彰 3社
   タイ創美 -- 品質
   RECTH    -- 供給
   ムラモト・エレクトロン（METCO） -- 開発

** 4月25日(土) CAT懇親ゴルフ実施。
  RESG/元山MDは和田取締役、渡部FGは細川副社長と同組でプレイ頂き
  非常に良い懇親が出来たと思います。
  また、西田EKにはCAT殿と共に幹事ご協力頂きましてありがとうございました。


