*  次世代画認ソリューション(N)電話会議フィードバック及び要望事項打合せ <2015-04-06 月>@ 15:00-17:00
** 中村様レジュメ
 1. 弊社より依頼している「ルネサス殿への依頼事項」に対する見解報告

 2. (N)殿向け提案内容に関する報告内容調整

 3. R-CarV2H廉価版SoC開発に向けた意見交換
  - 概要
    ⇒ R-CarV2H＋RcarV2H廉価版の2chip構成で、現R-CarV2Hシステムの
       性能不足分を対応することは出来ないかなど検討させて頂きたく。

    ⇒ (N)殿からは、現状×5倍の処理性能を実現する必要があるとのご意見を頂いています。

    当方としては、次世代SOCが、2018年頃の提供になる想定でも下記構成が実現できれば、
    当面（2018-19年位まで）の量産対応が可能ではないかと考えております。

  - 松モデル：メインSoC R-CarV2H ＋ RcarV2H廉価版 の 2chip構成
   ⇒ 実現機能：「高機能 自動駐車」，「特定環境での自動運転」の実現

   ⇒ 目標ECUコスト：2万円程度

  - 竹モデル：メインSoC R-CarV2H の 1chip構成
    ⇒ 実現機能：「普及型 自動駐車」の実現

    ⇒ 目標ECUコスト：1.5万円程度

  - 梅モデル：メインSoC R-CarV2H廉価版 の 1chip構成
    ⇒ 実現機能：「AVM＋限定した認識機能」，「Front，Rearカメラ」の実現
                低価格 AVM ECUの実現に向け

    ⇒ 目標ECUコスト：1万円以下

  - サブCPUについては、RH850シリーズのHighモデル，Lowモデルをシステム構成を考慮し、
    組み合わせて対応する必要があると考えております。

** 出席
   CL /渡辺B、中村K、久保田さん、緒方さん、岩田K、成田さん、今井さん、川口さん
   REL/大塚、星、小林
   REC/高草、藤巻
** 日産殿への回答期限 - 中村様
   4/08(水)に日産殿へ回答期限
   V2H廉価版は先々の話をしている中で、「では直近はどうするんだ？」と言われた時の為のもの
** 3/24 REL-日産/武田様 打合せの報告 - 大塚さん
   日産3/24にRELが日産へ別件で訪問
   資料：20150406Rene ADAS.pptx
*** 日時：3/24(火) 14:00-16:30
*** 訪問先：日産/IT&ITS開発部/武田様
*** 出席者：REL山越さん、中野
*** 日産自動運転（アプリケーション、SOP次期）：
   - 17MY リモート駐車/ガレージ駐車を目指したい。機能を実現するECUは
          クラリオン（V2H＋RH）が担当。
   - 18MY 高速道路走行。機能を実現するECUは日立AMSが担当（V2H＋RH）。
   - 20MY 市街地走行
           (*)ガレージ駐車は、自宅など決まった場所に何回か学習をさせて駐車するシステム。
              リモート駐車は、任意の場所（はじめての場所でも）で、自分のセンサーを頼りに駐車させるシステム。
             ガレージ駐車のほうがハードルが低いのと、日産上層部がガレージ駐車の需要があると考えている。

*** 20MYについて
   - Tier1へ、①スケーラブルなP/F設計②プロセッサの能力を要望しているとの事。
   - スケーラブルなP/F設計とは、変化が激しい世界なので、1～2年サイクルで開発が必要であり、ソフト/ハード互換設計のイメージ。
   - プロセッサの能力とは、17年末にAudiがNvidia/K1で自動運転を発表。
     このAudiが最初の自動運転のリファレンスになるはずであり、これが一つの指針になる。
    → R-Carの方が、消費電力/機能安全/価格で優位なのは知っているが、今回は性能を追求したい。
    → 但し、X1は消費電力の問題で車に搭載できるか疑問。
    → 機能安全は必須。Nvidiaへ機能安全の説明資料をもってこいと言うが、持ってこない。
       Nvidiaが日産上層部へ、OS(QNX)で機能安全ができているので問題ないと平然と言っている。
       上層部は、機能安全の中身も分かっていないので、ルネサスがアピールするには、
       日産上層部が分かるようなクリアなメッセージが必要。
    → 日産上層部は、Nvidiaのプレゼンを聞いて、Nvidiaしかできない機能があるから検討せよと
       言うが、そんな機能はないと思う
    → 日産上層部からは、Nvidiaを早く評価せよと言われている。来期にNvidiaをPOC評価する可能性あり。
    → R-Carは主戦場でも負けてない！X1と比較しスペックは負けているが、実行性能は同等と定量的に言えるか。。
    → Nvidiaを採用するなら、IVIか画認。ADASコントローラは無理。

    → V3H、V3Mを売り込むためには、ルネサスがやろうとしているPOC(V2H+STP with FPGA)で
       クラリオンの持っているVisual SLAMを実装して、STPをアピールしたらどうだろうか？
       現在、クラリオンからは、性能問題で、本来持っている性能から1/2～1/3までしか出てないと聞いている。

*** 競合他社状況
   - Conti、Boschは、機能安全面の問題で、Nvidiaは使わないと聞いている。
   - 今後、自動運転のところはIntelが出てくるのでは？ Telemaの技術を持っているQUALCOMMも可能性あり。

** QA
*** CortexR7搭載 = RH850不必要という認識でいいのか？ - 中村様
   ⇒ INTEGRITYの面倒をCR7で見るイメージ。デバイス1つで閉じるのは難しい?
*** 中村：X1との比較と言われた場合、どのように回答すればいいのか？
    大塚：対象はあくまでEyeQ4。X1はPC上のもの。
    中村：2020年をみた場合、X1クラスの
    大塚：演算性能＆車載対応が必要
    渡辺：X1の消費電力10Wは車載とみた場合何がネックなのか？
    中村：武田様は理解してくれているが、日産上層部に対しての説明が必要。
*** SoD 150mmsecが最終目標 (現在300mmsec)
    中村：日産からの要望性能はどのくらい？
    岩田：リモートパークの実現。
    中村：リモートパークの実現の為にはどのアプリがどの程度動けばいいのかリストアップが必要
    今井：結局今時点で満足出来てないんだよね？
    岩田：当初の要求から、車速が増えているのが原因。
          車メーカとして最先端の機能を要求されているので、ハードルがどんどん高くなる。

    岩田：日産のベンチマークはBMWやメルセデス。V2Hx2で同等性能出せるのか？が問われてる。

*** 車両スケジュール
    VC：2016年夏
    2017年：ガレージパーク (自宅駐車・自宅周辺の環境を覚える必要がある)
    2018年：リモートパーク
** 現行モデルの必要性能
   150316_次世代アプリ構成とPF要求 (rel_cl).pdf 4ページ目
   自動駐車～自動運転のアプリに対するPF要求
   左側の表はスラム除くガレージパークの必要性能
  - SLAM技術（Simultaneous Localization and Mapping ）：自車位置の推定とマッピング
** V2Hx2ヶ使いに対する要望とクラリオン想定ロードマップ
      2016年          2017年          2018年          2019年
*** 松:ASIL-C(D),コスト20K\
      V2H + V2H改                                     V3H + H3
      カメラ4or5入力                                  バレーパーク
      モニタ3出力                                     低速自動運転
      対V2H性能比5倍                                  カメラ7or8入力

*** 竹:ASIL-C(D),コスト15K\
      V2H                                             V3H
      カメラ4入力                                     リモートパーク
      モニタ2出力                                     カメラ4入力+フロント2入力
                                                      モニタ3出力
*** 梅:ASIL-B,コスト10K\以下
      V2H改                           V3M
      Front,Rear                      フロント/リアセンシング
      カメラ2入力                     低価格AVM+MOD
      モニタ1出力                     カメラ4入力
                                      モニタ3出力

*** View:ASIL-B,コスト10K\以下
      他社
      View(+MOD)
      ISO16505対応
      カメラ4入力
      モニタ3出力

** スケーラビリティ
   ルネサスとしてはR-Carシリーズでスケーラビリティを実現
  - [ ] ルネサスとしてV2H改の可否を検討する ＞ 大塚さん、小林さん
  - [ ] V2H廉価版を検討してみるに当り、CLの企画数量を提示して貰う ＞ 成田さん
** V3Hのコスト - 大塚さん
   現状だと40ドルになりそうだが、マーケとしてはその価格では売れないと考えている
   V3Hの性能 > V2Hを2個使い


** [ ] RH850+V2Hの場合のCPU間通信に関する見解が欲しい - 中村
* 議事録：藤巻さん
** 日 時：2015年4月6日(月) 15:00-17:45
** 場 所：CL C1/201会議室
** 出席者：CL/渡辺EB、中村M、岩田M、今井M、成田さん、久保田さん、緒方さん、川口さん
           REL/大塚さん、星さん、小林さん
           REC/高草、藤巻(記)

** まとめ：
   4/8(水)に(N)-CLで次世代画認ソリューションの打合せ予定((N)側：佐藤M、早川さん)。
   ルネサスも平行してR-CarV3xでのADASソリューションを(N)へINPUTする。
   但し、直近R-CarV2Hの性能改善見通しがないとインパクト弱く、4/7(火)AMにRenesas-CLで
   静止立体物検知アルゴリズム改善に向けた打合せを行う。
   また、19年までを考えるとR-CarV2H一個では性能不足が明白、R-CarV2H二個使いを
   検討する必要があるためR-CarV2H価格対応の検討依頼あり。
   尚、IS推進部/渡辺EBは4/1付で日産からの出向受け入れ。

** AI：
  1. CLへ添付資料送付 ・・・ (REC)
  →4/7、済み
  2. R-CarV2H価格対応検討 ・・・ (REL/REC)
  →CLに数量情報提示依頼中
  3. R-CarV3HとRH850/P1x-Cの通信I/F明確化 ・・・ (REL/REC)

** 内 容：
 添付資料に添ってADASソリューションを説明。
 R-Car+RH850で機能安全をしっかり対応する。
 将来的にはステカメ、サラウンドカメラをSUPER ADAS ECUで処理することを想定。
 MobileEye(Q4)を超える性能をR-CarV3Hで実現する。
 CoretexR7はAUTOSAR対応を想定している。
 (中村M)
 CR7あればRH850の外付けは不要か。
 CR7の有無で値差なければ良いが外付けにRH850が必要だと無駄な気がする。
 CR7の使い道が良く分からない。

 R-CarV3xでは3rdパーティーと連携してプラットフォーム準備することを考えている。
 Renesasから(N)にはnVIDIAでの量産はハードルが高い、但し性能は無視できない、
 Q4の性能をR-CarV3Hで超える、機能安全もやる、のストーリで説明を考えている。
 (岩田M)
 (N)から2018年を言われている。
 nVIDIAに対してはどう答えればいいか。
 →18年だとR-CarV2Hしかない。欧州はQ4、nVIDIAはあくまでPC。
   Q4は車載対応を宣言しているが、TEGRAはこれから。
   TEGRA=性能、Q4=性能+車載。
 (渡辺EB)
 ベンチマークはMobileEyeだけでいいか。
 nVIDIAは車載対応すると言っている、将来的にはTEGRAになるのでは。
 →消費電力10W、機能安全、車載品質を考慮するとTEGRAで製品化はできないと考えている。
 (N)武田さんはTEGRA採用は難しいと理解しているが(N)上層部がTEGRAで簡単に
 自動運転ができると考えている。
 TEGRAが車載対応できた場合にどうか、が説明できないと弱い。
 (N)の自動駐車も機能アップしているが、R-CarV2Hの性能に不満を持っている。
 TEGRAは何でも出来ます、R-Carのプラットフォームで日産のやりたい事が実現できるかどうか。
 R-CarV2H性能改善のゴールは。
 (岩田M)
 SODは100msec以内、4/E目標。5/Eに評価完。但し5/Eに性能出ない可能性もある。
 改善項目及び処理時間の改善見込みが必要。
 (渡辺EB)
 5/Eには現行アプリを余裕を持って回せる性能が必要。
 R-CarV2H二個使いで18年までやれるのか、の検討も必要。

 VClot：'16/夏
 '16/6E：R-CarV2H二個使いの判断
 17年はガレージパーク+SLAM(自宅周辺記憶)
 18年はリモートパーク(ここからは二個必要な可能性大)

 R-CarV2Hでもクリープ走行での性能は満たしているが、(N)要求仕様が代わり15km/hまで
 対応しなければならない状況。

 (岩田M)
 R-CarV3Hは18年サンプルか。
 →再度仕様検討中のため時期がグレー。
  仕様も高性能化、高機能化してしまい判断し兼ねている。
 (中村M)
 17-18年を考えた場合R-CarV2H二個使いの検討が必要。
 現行のR-CarV2H二個使いは(N)以外に売れずあり得ない。
 2入力/1出力、周辺カットで価格対応を検討してほしい。
 R-CarV3Hの価格は。
 →(N)には回答していない。
 まずはR-CarV2H一個使いで性能見極めが最優先。
 R-CarV3HとRH850/P1x-Cの通信I/Fの明確化もお願いしたい。
 (岩田M)
 (N)に対してはR-CarV3Hを19年のINPUTをお願いしたい。
