* フロントカメラECU
** 案件情報
2019年モデル
単眼フロント
先行開発
小型廉価センシング
対抗モービルアイ

*** 2カメラの用途
   - 距離を変える80mm、300mm
   - 運転者監視
   などの用途を考えている

*** 基板サイズ
   - 55mmx70mm(現行SH77652と同等モデル)

*** ターゲット価格
  - 7$ (年間50万台)

*** 開発日程(暫定)
   - 9月 環境構築
   - 年内 初回デモ

** e-SOL画認ミドルデモ <2015-07-03 金>@ 13:30-15:30 CL/C-1/1応接
*** 参加者
   - CL/高木様、新舎様、山本様、萩様、様、様
   - REC/高草、藤巻
   - e-SOL/金子さん
*** e-SOL紹介
*** Uncanny Vision社製 UncannyCV紹介 (ARM NEON搭載プロセッサ向け 超高速コンピュータビジョンライブラリ)
**** 最適化の仕組み(1)
    - ARM NEONの有効活用
    - 浮動小数点から固定小数点への書き換え
    - データの縮小化
    - ルックアップテーブルの仕様
    - データ転送の省略可
    - データの再利用
    - 積分画像(integral image)のしよう
    - アセンブリでのコーディング
    - C言語レベルでの最適化
    - アルゴリズムレベルでの最適化
    - キャッシュの有効活用
    - データプリフェッチ
    - マルチコア対応
**** 最適化の仕組み(2)
    - OpenCVと非互換
    - OpenCV：C++言語、UncannyCV：C言語
    - あせてOpenCVと互換性を持たせず、データ構造をNEONに最適化することにより、高速化
    - OpenCVとの対照表を用意
**** ライセンス
***** 無償評価ライセンス
     - オブジェクトコード(ライブラリ)提供
     - 全関数の評価が可能
     - 評価機関１ヶ月間
     - １回の評価で3000フレームまでに限定

***** 有償開発ライセンス
     - 250万円(開発ボード5枚)/年間
     - オブジェクトコード(ライブラリ)提供
     - 全関数の評価が可能
     - 量産使用不可

***** 量産ライセンス
     - オブジェクトコード(ライブラリ)提供
     - 製品単位または、機器・装置の出荷数量単位でのソフトウェア使用料または上記の併用
     - 必要な関数のみ、関数グループのみ、で契約・購入可

**** その他のサービス
     - カスタマイズ
     - 他プロセッサ/アーキテクチャへのポーティング
     - 新規アルゴリズムの開発
     - お客様のアルゴリズムの最適化
     - メールベースでの質疑応答
     - オンサイトサポート
     - トレーニング
*** QA
   - 山本様：ハードウェアアクセラレータ付きの製品と比較しての処理速度は？
        → H/Wがあるのであれば、そちらのほうが早いです。
*** デモ(ビデオ)
   |                               | OpenCV | UncannyCV |
   | カラー 492x398 CA15 800Mhz    | 1.8fps | 12fps     |
   | モノクロ 640x480 A8@1000MHz   | 30fps  | 80fps     |
   | OpticalFlow 640x480 A9@800Mhz | 7fps   | 18fps     |
*** RZ/A1Mでのe-SOL取得ベンチ
   - un_laneDeparture (VGA時) : 30msec
   - 外付けRAM動作時は遅くなってしまう為、内部RAMで完結するようにする必要あり。(10倍くらい違う)
*** QA
   新舎：複数アプリ動作でベンチ取って貰えないか？
   金子：何を動かすか指定してくれれば可能
         速度域等により動かすアプリを切り替えるのがいいかと思う。
         特に歩行者検知は重いので、全ての認識を同時に動かすことは周波数が足りない

   金子：コンパイラには依存するが、OSには非依存。TRONでもLinuxでも動く

   萩  ：uv_hogDetectMultiScale (179.29msec-QVGA) とはどんな処理？

*** 搭載アプリ
   - 白線認識、歩行者検知、車両検知
   - 最低でも上記3つ。実際にはさらに追加したい
   - 一概に30fps必要というわけではない。10fpsで最低限成り立つ。

*** A.I
   - ベンチマーク (RZ/A1版)
   - 関数マニュアル
   - センシングマイコン調査票のE2版作成

** R-CarV2H廉価版に対する必要機能ヒアリング <2015-07-21 火>@ 10:10-12:30 at CL/C-1
*** 参加者
   - CL/高木様、新舎様、山本様、萩様、宮本様
   - REC/高草、藤巻
*** デバイス選定メーカ
   - TI、フリースケール、ルネサス
   - 各メーカからの価格

画認アプリとしてはAVMとほぼ必要であると思われる

*** V2H
PKGの大きさも問題。コストも大幅に下げたい ← 現時点では他社デバイス選定の方向

7月中に仮決めし、評価ボード入手
年末にかけて評価。回路設計
年末に原理試作
9月末 ← 原理試作で最終デバイス搭載の為、設計期間の逆算を考えて。

7月末：やる・やらないの判断
8月末：概要決定
9月末：詳細決定

仕様min要求：他社デバイスとV2H廉価版を比較してあまりにも見劣りしていると厳しい
$7とかではないけど……。倍くらい？ (ECU販売金額は$100)
 - [ ] 猿田様、石川様とコストは相談すべし



自動運転の要求日程が前倒しされてきている。

商品企画
安いサン、かささださん

*** まとめ
  19年ターゲットにフロントカメラ（単眼or2カメ）企画中。MobileEye対抗。
  メインSoCはREL、TI、FSの3社で選定中。
  V2H、V3Mは価格、日程合わず他社品を第一候補に検討中。

  TO：小林（晋）さん、鈴木（政）さん、大塚（聡）さん
    このままだと他社品で試作他社品で着手しそうな状況です。
    R-CarV2Hカット、R-CarV3M前倒しなどCLへの提案方法について相談
    させていただきたく、来週で打合せ可能な候補日をいただけませんでしょうか？
    ご検討のほどよろしくお願いいたします。

*** 内容
  19年SOP、ECU価格$100ターゲット。
  メインSoCをREL、TI、FSの3社で選定中も第一候補は他社。

**** スケジュール
    ～'15/8：デバイス選定
    ～'15/12：先行評価（評価ボード）、並行して設計
    ～'16/1：一次試作
    '18：MP
**** 企画台数
    500K/年
**** 状況
  前方認識用カメラ一体型小型ECU、単眼or2カメラで認識アプリは白線、人物、
  動物、標識認識などを想定中も固まっていない状況。
  アプリ追加毎に数百円upなどの売り方ができれば、とのこと。
  実際試作を作ってOEMへ見せると仕様追加は充分あり得るため認識性能は
  R-CarV2H同等以上が必要。
  チップサイズも23mm□は大きく小型PKGが必要。
  R-CarV3MはR-CarV2H+Integrityで見込んだ性能が出ず苦戦している背景もあり、
  日程、仕様、性能面見えない部分がリスク。

  他社はIMPのようなハードIPは内蔵しておらずShaderエンジンを使っての認識。
  製品ラインナップも廉価～ハイエンドまでいくつかあり。
  フロント向け@1500イメージ。

  R-CarV2Hのカット版は？についてはカメラモジュールが次世代からMIPI対応も、
  そこを割り切れば問題なし。
  他社品と比較してルネサス品のメリットがあればもちろん検討する。
  提案可能であれば7/Eまでに一報欲しい。
  DU×1、VIN×3～4、IMR×2、3D、SDなどの周辺機能はカットで問題なし。

** R-CarV2H廉価版対応 内部打合せ <2015-07-27 月>@ 13:00-15:00 at REL武蔵
*** 出席者：REL/大塚（聡）さん、大橋さん、星さん、大森さん、小林（晋）さん
            REC/高草、藤巻

*** 背景、まとめ：
  クラリオンで'19ターゲットにカメラ一体型小型フロントカメラECUを企画中。
  R-CarV2H、R-CarV3Mで提案しクラリオン内一次選定を終え、FS、TI、RELの3社で最終選定中。
  クラリオンECU価格$100ターゲットからSoCのターゲット価格は@1,500。
  R-CarV2Hは価格、R-CarV3Mは日程が合わず苦戦中。
  第一候補FSのため、R-CarV2Hカット版、もしくはR-CarV3M日程前倒しをクラリオンへ再提案することできないか、内部打合せ実施。
  結論、R-CarV2Hカット版、R-CarV3M日程前倒し、いずれも提案不可。
  8月連休明けクラリオンに対しR-CarGen3状況をInputすることとした。

*** 内  容：
**** 開発スケジュール
    - '15/8：デバイス選定
    - '16/1：原理試作
    - '16/9：設計試作
    - '17/2：OEMへ提案
**** 企画台数
    1,500K/3年（'19～'21）
**** 選定状況
  クラリオン価格優先で選定中。SoCターゲット価格@1,500。
  R-CarV2Hは開発環境流用可能も価格合わず、R-CarV3Mはイメージ一年日程が合わない状況で苦戦中。
  画認性能は見えない部分あるが、製品ラインナップ、価格からクラリオンはFSを第一候補に最終選定中の状況。
**** REC懸念事項
  フロントカメラに参入された場合、'20以降のアラウンドビューモニタECUへの影響が読めず、R-CarV2Hカット版、R-CarV3Mの日程前倒しについて検討したが
  結論としてR-CarV2Hカット版対応不可、R-CarV3Mも回答済みの日程（WS：'16/3Q目標）を再度Inputし、'16/9の設計試作タイミング目処に置換え提案を行う
  また、8月連休明け目処にクラリオンへR-CarGen3の状況Inputを行う。

** フロントカメラ向けV2H Cut版内部打合せ
*** REL内部打合せ結果
  １）V2H Cut版の対応  NG
  ２）V3Mの19MYへの前倒しもNG
  となり、今ある製品で提案する結論になったようです。
*** M2N提案の背景
  夕方のカメラ定例の中で、M2NのＯｐｔｉｏｎでＩＭＰが内蔵されているか確認した結果、Ｍ２Ｎにも
  ＩＭＰが内蔵されているとの事からＭ２ＮのＩＭＰ公開を議論したい旨、自日営には打診しました。

  このままでは、ＣＬに対して断り回答となってしまい、対抗他社（ＦＳ、Ｎｖｉｄｉａ）に参入される
  可能性が高い為、上記案のたたき台をＲＥＣ内で作成し、自日営及びＡＤＡＳに提案したく、思います。
*** 打合せ内容
   1. ＣＬフロントカメラビジネスの精査と売上げシュミレーション
   2. Ｍ２Ｎ  ＩＭＰ内蔵版仕様確認


** 廉価V2Hお願い
@1,500-という価格は破格である。
この価格と言われた場合、「クラリオンは落としても構わない」と思ってしまう。

CLヨーロッパの案件との繋がりについて
案件としては完全に別です (伏見)

須貝さんからはまだアナログカメラと言われていたが、デジタルに一気に変わるのか？
フロントカメラは解像度が求められており、またクラリオンの付き合いのあるカメラメーカからは
2016年から順次デジタルカメラが拡大していくと聞いている

R-CarV2Hフル版へ値段波及しないのか
その為に、V-IN制限の製品の設定をお願いしたい

◆ルネサス状況
IPはルネサス全体で管理しているので、CL向け特殊品の設定は出来ない。
標準品として設定するしかない

RECとしての一番の懸念はフロントカメラでアプリ開発を行ったことで、AVMミドルクラスにも
波及されることを懸念している (伏見)

◆REE CLヨーロッパへのフライング回答時のデータ
V2Hの$16.1K (GP50%) => \1,771-(\110/$)

** V3M日程対応のお願い版資料も作る
REC A.I.
TIの回答価格チェック (FSならば価格負けてもいい=>取られてもいい)
他社採用時のアルゴリズムをどう考えているのか？
TI採用でも差別化できるアルゴリズムが出来る分けがないので、どうぞお使い下さい。でいいぞ。
