* R-CarV2H+RH850/F1LシステムでのASIL対応について <2015-03-26 木>@ 15:30-17:30 at CL/C-2/30F 16応接 :ISO26262:
** レジュメ
 1. 技術安全コンセプトN-AP_安全要求票20150205メンテ中 - コピー.xls
  1. 「IPA【TSR_TSC】」シート
     ～*IPA SG表 ⇒FSR/TSR/SSR/HSI 展開表  （旧帳票）
  2. 「6-1 (AP_SG1)」シート
     ～IPA SGを元にした⇒自動駐車（新帳票）FSR/TSR/SSR/HSI 展開表1/2
  3. 「6-2 (AP_SG1)」シート
     ～IPA SGを元にした⇒自動駐車（新帳票）FSR/TSR/SSR/HSI 展開表2/2
  4. 「N-APブロック図」シート
     ～機安システムブロック図（ECU外の車両側システムにおいては予想の範疇 で記載）
  5. 「ECU内」シート
     ～機安システム（HW Ver）ブロック図（ECU外の車両側システムにおいては 予想の範疇で記載）
 2. 次期日産IPA_ブロック図（メンテ中）_20150310.pdf
   ～自動駐車ECU内 ブロック図
 3. 次期日産IPA_ブロック図（メンテ中）_20150310.電源系統pdf.pdf
   ～自動駐車ECU内 電源系統図（メンテ中、1次試作のものとなります。)
 4. 次期日産IPA_ブロック図（メンテ中）_20150310reset.pdf
   ～自動駐車ECU内 Reset系統図
 5. NAP SM List_20141023.pdf
   HWアーキテクチャメトリクスにおけるSM一覧リスト。
** RH850採用MCU (暫定)
   R7F7010303AFP, ROM:1.5M\, PKG:144pin
** 有償版 FMEDAツールの紹介
** 藤巻議事録
*** 日 時：2015年3月26日（木） 15:30-18:00
    場 所：
    出席者：CL/森澤さん、吉岡さん、川口さん
            HiENG/渡邉さん
            REL/砂田さん、提さん、小林さん、鈴木（政）さん
            REC/高草、藤巻（記）
*** まとめ：
    開発中のN向け自動駐車システムのASILとしてはC(D)になるとのCL想定。
    CLからフォローはしているようだが、NからのSG提示は5/M。
    CL側でC（D）を想定し担保できるシステム構成を試行錯誤している状況。
    継続RELの機能安全&サポートパッケージを検討いただくこととした。

*** AI：
 - [ ] セーフティメカニズムでハード/ソフトどちらで実現するかの資料提出
 1. RH850/F1LのFMEDAに記載あるSMは、ハードウェアで担保しているものなのか、
  ソフトウェアで担保しなければいけないものなのか、が分かる資料の提出
  ・・・ ～4/1、REL/REC

  TO：鈴木（政）さん
   打合せでありました上記AI資料、お手数ですが送付いただけますようお願いいたします。

*** 内 容：
   （CL状況）
    3/3にN-CLで打合せし、SG出る予定も結果出ず。
    3/Eに再度打合せアレンジ中だったがN都合で4月以降へシフト。
    CLからは'14/10からSG提示の要求しているがNからは'15/5Mの回答。
    CLは何でもいいから情報提示の要求をしている状況。
    Nからは、
     加速系：ASIL-B、C
     減速計：ASIL-C、D
    だと言われているようで、自動駐車システムのCL想定はASIL-C（D）。
    AMSのADAS-Boxでデコンポジションされることを期待している。
    EngineeringSampleが'15/12E。ここまでに評価完が必要。
    FSR(TSR？)承認が'15/6E、SafetyRequirementが'15/11。
    ADAS-Boxとの関係は添付(CLがプロジェクタ表示していたものの書き写し)。

   (ディスカッション)
    日程的に正式開発プロセスに則る事ができない。
    RH850/F1Lは144pin、ROM：1.5MB、RAM：128KBで量産する見通し。
    RH850/F1LのFMEDAに記載されているSM、カバレッジはAnnexDに
    記載されているもの(99%、90%、60%など)。
    このまま海外へ持って行くとNGなケースが多い。
    FMEDAに記載されているSMはどこで担保しなければいけないものなのか
    分かる資料が欲しい(CL)→Yes(REL)、別途提出する。
    機能安全&セキュリティパッケージプログラムでは回路レベルでのFMEDAも準備中。
    根拠もODITのような形でRELで説明し、社内認証証明書も提出可能。
    また、FMEDAのカスタマイズ可能なxlsツールも用意済み。
    実際xlsツールでのカスタマイズ項目などを見ていただいた。
    (DVF=そのままだとSPFになる、IVF=そのままだとLFになる)
    CLシステムの中でのデコンポジションはまだ検討できていない。


