* [QA表No.105]VSPDドライバ(砂嵐対策検討)打合せ <2015-03-24 火>@10:00-12:00 at ルネサス武蔵/７会議室
** [C] 現在、砂嵐問題が発生しているため、この対策を行いたい。
    砂嵐の問題は、IMRの縮小で画素が間引かれ、隣り合う画素のテクスチャが目立ってしまう事で
    発生しているのが要因と想定。
    それの対策として、OIL上ではVSPとIMPを用いた対策案を提案いただいたが、
    IMPはこちらの内部の作りの都合上、使う事ができないため、VSPで対策する事を検討している。
    VSPSは使えるメドが立っているが、VSPDの方が現状で制限が多く、対策のメドが立たないため、
    本問題について、対策案を相談したい。

** [R] 砂嵐問題はIMRの欠点ではある。
    （縮小時、バイリニアをかけるとエイリアスが出てしまう点）
    VSPでアンチエイリアスをかけるというのが、OILで提案した対策内容。
    VSPDでの拡大は推奨できない。

** [C] デジタル出力の場合、一度VSPSで「縮小」し、その後、VSPDを使った「拡大」を行いたいが、
    VSPDが使えないとなると、VSPSで縮小後に再度拡大をする必要が出てきてしまい、厳しい。
    （VSPSがリソースの取り合いをする懸念がある。）

** [R] 一つの対策案としては、フィルタを掛けたものと掛けていないものを組み合わせる方法も考えられる。
    あまり縮小をされてない部分（カメラの焦点から外れた部分）はフィルタをかけず、
    縮小される部分（カメラの焦点に近い部分）はフィルタを掛けるなど。
    イメージ的には、1280x720の絵と720x480の絵を組み合わせて一枚の絵を作る感じ。
    ルネサスの内部で試しに動かしてみた結果、そこそこ問題は出なかった。（ただし静止画）

** [C] 等倍でVSPをかけるとローパスはかかるか？
    →[R]掛からない。
        バイキュービックのときだけローパスがかかる

** [R] IMRで視点変換する際、縮小するようなケースでは、バイリニアを掛けると
    エイリアスが目立ってしまうのが今回の問題の発端なので、
    IMRの前段にてVSPで縮小し、小さくした映像をIMRで拡大すれば同等の効果は得られる。
    （ローパスフィルタを事前にかけてエイリアシングを防ぐ）
    つまり、VSPSで縮小したものをIMRで拡大（マップで拡大）するという案。
    これが一番お手軽な方法。

** [R] 今回の問題は、次の世代では改善をする必要があると認識している。
    多段階の縮小率を選べるようにする。

** [C] 最初に提案頂いたフィルタを掛けていない元画像とフィルタを掛けた加工済みの
    画像の両方（1280x800と720x480の画像を張り合わせるような感じ）を使う対策案は、
    画像の管理が大変（映像の上書きを防止する仕組みが必要）なので、現実的な対応案ではない。

** [R] VSPDでの拡大はできない。
    そもそも拡大・縮小が出来るモジュールではなく、DUの帯域の中でプレーン同士を
    張り合わせる事しかできない。
    よって、CL側の想定されている使い方には現状で対応できない。

** [R] VSPSのフィルタの設定は、以下の3つのフィルタがあるが、、、
        バイリニア
        ニアレストネイバー
        バイキュービック（マルチタップ）
    上記の中でローパスフィルタに相当するのはバイキュービックのみ。
    [C]現状では、バイキュービックを掛けている。
        [R]バイキュービックで問題なし。

** [C] 上記のH/W側のフィルタ設定について、さらに有効なローパスフィルタの設定方法について、
    ドライバのソフトウェア的な使い方（フィルタの設定方法）は具体的にどういうやり方がある？
    （VSPSの有効なローパスフィルタの指定方法は？バイキュービックのフィルタ設定時に設定内容をいじるとか）
    [R]バイキュービックのローパスフィルタのパラメータは特にいじらない。
       よって、バイキュービックをかけて終わり。
       縮小率の推奨値がある。（ドライバの設定を変えればフィルタ強度の調整は可能）
       現状見えているI/Fは変更できないので、ドライバの中で直叩きしているところを直接いじれば修正可能。

** [R] VSPDは、一応、今後リリースを予定しているが、機能拡張はしない予定。
    （リリース時期は、3月ENDを少し越えるあたりで。。。
      リリースする際の内容としては、フレームバッファAPIに対応するだけで、
      機能追加のものを作る予定はない）
    ルネサス側と、使う側とで想定される使用状況が会わず、使う側の想定を全て網羅するドライバを作るのは難しい。
    使う側が、考えうる理想の使い方をしたい場合は、今のサンプルを見て改造してもらうしかない。
    その場合、ハードウェア的なガイドはするけど。。。

    元々VSPDはDUを補間する程度の動きをルネサス側としては想定していた。
    （VSPDはDUと内部バスで同じところに繋がっているので、メモリの帯域が同じで、
      速度的なメリットがあるので。。。）
    ただしそもそも拡大・縮小などができるモジュールではないので、CL側で想定していた使い方をするものではないし、
    今後機能拡張する予定も無い。
    今回の対策を行うには、VSPSを使う方が圧倒的に良い。

** [C] VSPDでの拡大は推奨できない、との事から、IMRの前段でVSPSによる縮小後、
    IMRのマップで拡大する方式で対策を行う事とする。
