* IODEVICE / 画像認識 高速化：進捗連絡会 <2015-03-23 月>@ 18:00-19:00 at 電話会議
** 高草議事録
*** 宿題事項
 - [X] 3/25 CVlib改善版の検証結果報告 <= クラリオン
 - [X] 3/31 3/27  MSIOFのデータジスタアクセスのシミュレーションの結果報告
 - [X] 随時 IMPlib改善版のタイムエラーへの対応
 - [X] 3/25? キャッシュのパージ(メモリドライバ)改善。
             ルネサス版としてまずはリリース。
             CL環境にルネサスが組み込む。その作業は別途電話会議で行う。
 - [X] メモリリージョンオブジェクトの生成・破棄 <- クラリオン側作業とする。
 - [X] 3/27 CVlib:割り込み減少対策に関する影響範囲報告。(画面端でフィルタ処理出来ない)

*** 出席
   CL/岩田様、加藤様、高田様、ただの様、萩様
   REC/高草、藤巻
   REL/大橋さん、星さん、木村さん、小林
   HiICS/戸塚/斉藤
   ADaC/慶野

*** 3/20リリース分の説明 by 星さん
    カーネルコールをしないプレーンバッファ。6%改善済。

*** リリースソフトの組込結果 by 加藤様
   IMPライブラリはタイムエラー発生でREL側で確認作業中
   IMR・CVlibは組み込んでおらず。
   ルネサス側作業に時間がかかる為、CVlibを先に検証頂くこととした。

*** usleep/IODEVICE 期待動作できていない ADaC/慶野さん
   正常状態と負荷状態の比較調査中
   現象は見えてるものの、原因までは掴めず。
 - 再現環境立上げに手間取っており、目処立たず。都度報告する。
 - GHSからの回答未入手。回答予定日未定。

*** MSIOFのデータレジスタアクセスに約320usec掛かっているのは妥当なのか？
 - シミュレーションの結果を報告する。3/27迄に回答する

*** アドレス取得
    キャッシュのフラッシュ改善
    レジスタアクセス改善

*** 3/23週 活動
 - IMPタイムエラーへの対応
 - キャッシュのパージ(メモリドライバ)改善。
      ルネサス版としてまずはリリース。
      CL環境にルネサスが組み込む。その作業は別途電話会議で行う。
 - メモリリージョンオブジェクトの生成・破棄はクラリオン側作業とする。
 - CVlib:割り込み現象対策に関する影響
   画面端にフィルタ処理が出来ない。影響範囲について3/27迄に報告。
 - CVlibドキュメント発行

* 加藤様議事録
** 出席
15/03/23 
 ルネサス
   星様、木村様、大橋様、小林様
 ルネサスイーストン
   高草様、藤巻様
 ADaC
   慶野様
 HiICS
   佐藤(路)様、斎藤様、川上様
 日研
   宇田川様、伊藤様
 Clarion
   岩田、吉岡、萩、唯野、高田、甲斐、加藤

** 星様のご説明
 No.2のソフトをリリース
    ・CVLib
    ・IMR
    ・IMP
 No.1のパワポ資料をリリース
  アドレス読み出しをキャッシュして改善⇒約６％の改善効果

** 組み込み確認の連絡
 星様にソフトを渡して確認して頂く
 IMP以外については組み込み完了
 CVLibが動かせていない：確認できていない
 CVLibの確認を優先して作業する
 CVLibを確認する際、IMPのカーネルドライバを組み込んでおく＞了解です

** 慶野様のご説明
 No.9,No.10の現象はつかめているが原因まではつかめていない
 見通し＞再現環境の立ち上げに時間がかかっていた
     どのぐらいかが未定＞逐次報告する
 GHSからの回答が来ていない
 ２コアについての見解など連絡貰えていない
 ＞早急に回答を要請する（今月中に回答を貰う）

** No.7について
 u-boot v1.07をリリース 宿題＞Clarion

** No.6について
 ハード部門でシミュレーションを実施し結果を報告
 ＞今週中に連絡

** 提供コードに関する残課題：
Flash=キャッシュのパージがかなり呼ばれており、その改善が効果がありそうである＞メモリドライバの改善１～２日
最終効果確認はClarionの環境で行って欲しい
 一旦Clarionに渡してマージして作業再確認するのは非効率である
 電話会議接続して手を入れる作業をする＞ルネサス環境で織り込み完了時点で実施

** No.3について
前段(フィルタ処理)、後段(追跡)と分けることができ、前段のところを改善する検討をしている。
検討内容：割り込みの回数（キャッシュ操作)を減らす。（ルネサス環境で確認中）＞性能劣化の割合が低くなる
     処理時間が長いことは、CVLib内における待ち時間が長いことが影響しているものと考えている。
この検討内容により、画面端における処理結果が少し変わる。
 →現状、画面端のフィルタ処理をソフト処理で外挿しているが、外挿しないようにする。
  画面端のみフィルタできないので縮小時に悪影響する。
 →正確には、ウィンドウ端の結果が変わる。
今週中にクラリオン環境に組み込んで確認予定。
LK OpticalFlowの処理に関して、ウィンドウ(ROI)設定ができない件について、同時に対策を入れる。

** CVLibのLKについて正式版マニュアルをリリースする。"

** 改善版の評価結果が早くて今日中or明日午前中
CVLibを使う頻度が少ない。
タイムアウトの方はまた明日報告する

** 星様＞現状の評価も実施しており、上がっている問題以外にも項目あればあげる

** ADaCの調査について3/27までに回答

** 次回打ち合わせ
 改善版の評価内容に応じて緊急で実施するかを判断する
 30日(月)18:00～に3/27回答のものの確認項目についての回答
* [[file:c:/Users/908658/Dropbox/soft/howm/mail/%5BRCV2H%5D%E3%82%AF%E3%83%A9%E3%83%AA%E3%82%AA%E3%83%B3%20%E3%83%91%E3%83%95%E3%82%A9%E3%83%BC%E3%83%9E%E3%83%B3%E3%82%B9%E6%94%B9%E5%96%84%E9%80%B2%E6%8D%97%E9%80%A3%E7%B5%A1%E4%BC%9A(3-23%E3%80%811800%EF%BD%9E)_20150323_fujimaki.eml][藤巻議事録]]
