* クラリオン RH850/F1K紹介、(N)カメラECU機能安全対応打合せ <2015-05-11 月>@ 16:30-17:30
* 議事録：藤巻
** 開催概要
    □日  時：2015年5月11日(月)  16:30-18:00
    □場  所：クラリオン C1/2Fロビー
    □出席者：中村M、川口さん、岩田M、吉岡さん、甲斐さん、森澤さん
                REL/小林K、鈴木(政)さん
                REC/高草、藤巻(記)
** まとめ：
      RH850/F1Kの紹介を実施しRH850/F1Lとの違いは認識していただいたが、
      直近(N)向けカメラECUのASIL-D対応に四苦八苦している状況。
      RH850/E1L提案するもIO電圧5V(R-CarV2Hは3.3V)のためNGの判断、
      再度RH850/P1xを推奨する方向で進める。
      が、デバイススケジュールと開発期間がネックのためCLの希望としては
      現在開発中のRH850/F1LでASIL-D対応する手段を検討したい、が第一候補。
      継続状況ヒアリングする。

** アクションアイテム：
  1. RH850/P1x関連情報の送付
    (1)ハードウェアマニュアル  ⇒  5/11対応済み
    (2)開発スケジュール(PKG毎にWS、CS、MP)  ⇒  REL/REC(5/12)
    (3)プレゼン資料  ⇒  REL/REC(5/12)

  2. RH850、機能安全知見者との打合せ  ⇒  REL/REC(可能早期)

    TO：鈴木(政)さん、小林さん
      先日は打合せへのご対応、マニュアルリリースいただきありがとうございました。
      急ぎのお願いとなり恐縮ですがRH850/P1xの開発スケジュール、プレゼン資料に
      ついて本日中にご連絡、送付をいただきたくよろしくお願いいたします。
      また、RH850、機能安全知見者との打合せは候補日、場所を提示する形で
      進めたく思いますので、お手数ですが人選、日程調整お願いさせていただきたく、
      よろしくお願いいたします。

** 内  容：

      添付資料にてRH850/F1Kの紹介を実施。
      CAN-FD、機能安全機能強化、ASIL-Dまでは対応しない、で理解いただいたが
      直近(N)向けカメラECUではやはりASIL-Dが必要とのこと。
      ASIL-Dになるとロックステップデュアル機構が必要になるが、RH850/E1Lは
      IO電圧が5VのためR-CarV2Hと繋がらなくNG。
      Eシリーズ、Pシリーズなどは基本的に単品使いを想定した仕様になっていて
      使いづらい。R-Carとセットで使えるASIL-Dマイコンが欲しい。
      R-CarV2Hを二個使いした場合単純にFIT値が倍、より高いASILを担保できる
      マイコンに置き換えることでFIT値を下げたい、とのこと。

*** CL開発スケジュール
        '15/5E：回路Fix(大至急デバイス選定必要)
        '15/7F：デバイスサンプル要
        '15/12：EN完(CS品)
        '16/8：AP(MP品)
        '17/1：SOP(MP品)

*** 機能安全について
      YogitechにはR-CarV2Hコア診断プログラムのみ見積もり依頼中。
      Yogitech、RELと会話していた中でR-CarV2H+シングルコアマイコンでASIL-Dは
      出来ないと認識したが、今回のカメラECUは自動駐車だけではなく、一部自動運転にも
      流用する必要が出てくるため、直近どうにかASIL-Dを満足させたい。
      '15/12には評価Fixの必要あり、実際問題マイコンの置き換えは難しい、ソフトも
      ITRON上に実装しておりRH850/F1Lの複数個使い、RH850/F1Hでのなんちゃって
      ロックステップ機構で凌げないか、など検討中。
      一度RELの知見者とRH850/F1x、P1xそれぞれでASIL対応可否について方向性を
      議論させて欲しい、場所はどこでも構わないので検討お願いしたい。
      (N)からは未だにSG、ASIL、はっきり出てこない状況。
      CLはSGとして高速走行時(15Km/h以上？)にステアリング、アクセル、ブレーキ
      制御信号を出さない、低速走行時に誤データを出さない、を想定。
      ステアリング、アクセル、ブレーキの各ECUは個別にASIL担保するが、カメラECUの
      ハードウェアはデコンポしても(D)がついてしまうとのこと。
      5/12(火)にCL内部会議がありデバイス選定含め議論予定、そのためRH850/P1xの
      ハードウェアマニュアル、スケジュール、プレゼン資料がほしい(5/12中)。
      REL品でNGな場合は他社品含め検討する必要あり。

*** 次世代システム構成
      次世代ではR-CarV3x + サブマイコンのキットとしてASIL-Dに向けたアプローチ、
      提案をして欲しい(同じREL製品なのに何故キット提案出来ないのか、と指摘あり)。
      また、今後AMSとCLへ出す情報の整合を取ってほしいのリクエストあり。

