* HI.CommunicationEngine不具合 (CL/山内様、清水様)                      :TCU:
** HI.CommunicationEngine DNSに関する質問
 - RSPT/武井様 (masahiko takei <masahiko.takei.nx@renesas.com>)
*** 質問内容 03/31
   ⇒関数gethostbynameが関数DNStsk_MakeHostEntをcallする際に、関数DNStsk_MakeHostEnt
    内部で関数DNStsk_CopyHostNameをCallする時に、Access Exceptionが発生しました。

    Access Exceptionが発生する原因は、関数DNStsk_MakeHostEntと関数DNStsk_CopyHostNameに
    関わりますので、この二つ関数のソースを提供頂くか、難しい場合は、Access Exceptionが
    発生する要因をご教授頂きたい。
*** 一次回答 04/02
   RTSPで現象を確認
   ホスト名の長さが44バイトを超える場合、CPUアドレスエラーが発生する場合がある
   (マニュアル上では、255バイトまでのホスト名に対応しています。)
   現在、回避策等を調査中です。回避策等わかり次第、至急ご連絡致します
*** 確認依頼 04/02
   「対応策」と別に、「原因」がすでに明確になっていればお教えください。
  （現在リリース済みの製品に影響があるのかどうかを知りたい為）
***  原因 04/02
   ホスト名が22バイトを超える場合、内部で複数の格納領域を双方向キューで繋ぎ、管理しますが、
   そのキューの繋ぎ方に問題があり、キューが2つまでは問題は発生しませんが、
   3つ目のキューを繋ぐと問題が発生します。
   ＤＮＳソースの不具合なので、対策版を早期に提示するよう内部調整しております。
*** 対策版対応日程
   4/3      問題箇所の修正、他のキュー操作確認。α版をメール送付。
   4/3～4/4 他機能の確認。テスト実施。
   4/6      他機能の確認で問題あった場合、β版（製品版と同じレベルのもの）の提出。
   4/7以降  技術情報発行、差替え版送付。
*** 質問と回答 4/03
 1. 今回の問題を抱えてる対象は今回見つかった、下記製品だけですか？
    製品名：TCP/IP プロトコルスタック HI.Communication Engine
    http://www.rspt.renesas.com/solution/hice-index/

   →今回問題が見つかった製品は、HI.ComunicationEngineのオプション製品の
     HI.CommunicationEngine-DNSクライアントのみとなります。

 2. 上記1に関連しますが、横展開が必要なスタックは他にありますか？
    (同じ不具合を抱えてる製品)

   →今回の不具合はHI.CommunicationEngine-DNS固有の処理部分が問題と
     なっており、他の製品においては同様の問題はないと考えております。

 3. 上記2の横展開が必要なスタックを含め、同じような現象が出る
    スタックを、CL内のどの部門で使われているか(販売したか)を調べて
    頂きたく。
    (異動/退職もあるので部署名+担当者+時期を知りたいです)

   →HI.CommunicationEngineのTCP/IPプロトコルスタックはTCU部隊様
     以外への販売実績はございませんでした。

 4. 修正案について、方針、制約等、事前に教えて下さい
    (スタックを使う側に制約が入るのか、置き換えで良いのかを含め)

   →APIのパラメータが変わるような変更はない為、
     HI.CommunicationEngine-DNSのライブラリファイル(relファイル)を
     入れ替えるだけで良いです。アプリケーション側に制約は発生しません。

 5. 治っていることを、CLではどのように確認できるかを提案下さい。

   →DNSのgethostbyname()にて、今回問題が発生したような長いホストの
     公式名(44バイトを超える名称)を返すホスト名を指定することで確認できます。
     gethostbyname()にて取得できたホストエントリ情報のホストの公式名が
    正しければ、修正されていることが確認できます。
** HI.CommunicationEngine DNS不具合打合せ <2015-04-06 月>@ 10:15-12:00 at CL/C-1
*** 出席
    CL/設計, 品証, 他調整中
    RSTP/
    REC
*** アジェンダ
 1. 原因
 2. 対策
 3. β版の試験状況, 正式版リリースに向けて確認
 4. 使用/組込上の注意
 5. CLのどの製品に影響を与えるか

*** A.I.
 1. DNS修正に関するテスト項目を開示・・・・・・・DNS正式版提供時

 2. DNSソースコード提供（無償） 覚書で対応・・・DNS正式版提供時

 3. SH4A(ナビ)対応で提供している上位プロトコルの調査

 4. 類似不具合確認を実施 ・・・・・・・・・・・・確認完了時期を別途連絡
    l  テストについて、マニュアル記載の境界値確認を実施。
** HI.CommunicationEngine DNS不具合 追加一件発覚 4/07
 1. 概要
   複数のサービスポイントIDを使用し、サーバに対して同時に
   複数のDNSリクエストを発行した場合、最後に送信したリクエストの
   応答しか受信できない。

 2. 詳細内容
   クライアントは、送信したリクエストパケットの"送信ID"と一致しない
   IDを持つレスポンスパケットを受信した場合、破棄するようになっている(正常な仕様)。
   この送信IDは、サービスポイントIDにかかわらず、リクエストを送信する直前に
   ＋1している為、複数のサービスポイントID(最大4つ)を使用し、同時に送信した場合、
   応答を受信する前に次のリクエスト送信によって、送信IDが＋１されてしまう。
   その結果、同時に送信したリクエストの最後のレスポンスパケット以外は、送信IDと
   一致しないこととなり、不正に破棄されてしまう。
   なお、同じサービスポイントIDでは、複数のリクエストは送信できないようになっております。
   (1つのリクエストの処理中に、他の要求を行った場合は、DNSERR_OBJ(その他の状態エラー)
   を返します。)

 3. 対策内容
   サービスポイントID毎に送信IDを管理し、サービスポイントID毎の送信IDと、
   受信したレスポンスのIDを比較するよう対策する。

 4. 対応スケジュール
   4/8(水) 上記不具合の対策完了。β版を提出します。
   4/8(水) TCP、PPP、FTP、DHCPの類似調査を実施します。
   4/9(木) 正式版を送付します。

** 清水様 質問事項 4/07 - 4/08回答
 - 上記現象が発生すると具体的にどのような問題が発生しますか？
   (名前解決ができない/Rebootが発生するなど)

  ⇒ 名前解決が出来ず、DNSERR_NOREC(ネームサーバの応答がない)エラーが発生します。
     Reboot、アドレエラーは発生しません。

 - 上記現象は、DNS関連関数コールのリトライで復旧することが困難なエラーでしょうか？

  ⇒ DNS関数コールのリトライを行い、再度リクエストを発行することで、正常に名前解決を行う
     ことができます。

 - 現在の弊社実装が上記の現象を発生させているかどうかを確認する手段をお教えください。
    ->複数のサービスポイントIDを使用している/していない。
    ->サーバに対して同時に複数のDNSリクエストを発行している/していない。
    ->最後に送信したリクエストの応答しか受信できていない/その他の応答も受信できている。
    （○○関数戻り値が□□エラーなど）

  ⇒ ①複数のサービスポイントIDを使用していないのであれば、発生しません。
     ②サーバに対して同時に複数のDNSリクエストを発行していない場合でも、サーバからの応答を
       受信する前に、他のサービスポイントIDからDNSリクエストを発行した場合は発生します。
     ③最後に送信したリクエストの応答しか受信できません。それ以前のリクエストは、関数の戻り値
       がエラーとなり、エラーコードはDNSERR_NOREC(ネームサーバの応答がない)となります。

*** 追加質問 清水様 4/08
   >   ⇒ ①複数のサービスポイントIDを使用していないのであれば、発生しません。

   マニュアル（「DNS_RM.pdf」）の
   「2.1.2 ホストデータベースの初期化とDNSクライアントの開始」関数：
   ER ercd = DNS_start(T_DNS_INI *par );
   のパラメータ（※）の内、「maxsvpid」に「1」が設定されていれば、
   本問題は発生しない認識で良いでしょうか？

   それとも、「maxsvpid」が「1」に設定されていても、
   「DNS_start」関数コールを複数回実施していれば、
   本問題が発生するのでしょうか？

** リリースについてのお願い事項 山内様
  1. 2点の対策が入った版のリリース(現在CLで開発中機種用)
  2. CLで使用中の版から最新版までの対策内容がわかるドキュメント
  3. CLで使用中の版に45byte問題"だけ"を対応した版のリリース(量産済機種用)
     (量産済み製品には変更を最小限に留めたいため)

*** 1について、確認です。
   リリースされるのは下記2点のどちらでしょうか？
    a. 当時のVersionに、今回の対策(2点)を施す
    b. 最新版に今回の対策(2点)を施す

   上記aの場合、既知の不具合が気になります。
   致命的な不具合がなければ開発中の機種でも「当時の版に対策」を使います。

   上記bの場合、DNSを改修することにより、CL側の潜在Bugがこんにちわを
   しないか心配です。
   変更箇所ならびにその影響をヒアリングした上でCL側もテストをやり
   治す必要が出てくるかなと思っています。
   (完全に切り分けられて隠蔽できる、というのであれば良いですが。。)
   これらをJudgeするためにも上記2のドキュメントをお願いします。

** 複数サービスポイント不具合説明 <2015-04-20 月>@ 10:15-12:00 at CL/C-1
  4/10(金) 現行モデルについて４５バイト問題のみ連絡
  複数サービスポイントについてCL該当なしと判断し、ユーザーへ連絡していない。
*** 出席
   REC/山内様、信田様
   RSPT/武井さん、芳賀さん、遠藤さん
   REC/高草
*** 45バイト以上不具合の原因及び再発防止策 (遠藤さん)
   - テスト仕様DRを見せて欲しい
   - TS規格で制定した時に過去のソフトの再テストを行わなかったのか？ (信田様)
   - 水平展開漏れが流出原因ではあるが、今後水平展開漏れについても規程願う (信田様)
*** 複数のDNSサービスポイントへ同時リスエスト送信時の不具合 (芳賀さん)
*** 質疑応答
   - 評価はやっぱり人力しかないのか (山内様)
    → 評価ツールは導入しているが、最後はやっぱり人力
   - ユーザから追加の評価要求があった場合に対応して欲しい
   - 最小最大境界だけでなくnull値もチェックしているか
    → しています
*** ユーザへの説明
**** 現行モデル
    対策組込んだ上でユーザへリリース
    量産中モデルはユーザへ何も
TCUは3社に納入中
 N:市場処置のみ
 H:量産中モデルあり
 もう一社ある


