* GHS来日MTG  <2015-07-14 火>@ 09:30-11:30 at ルネサス武蔵/第七会議室
** アプリ処理時間速報 (average)
  - 前回より機能アップデートあり。バス負荷問題あり。OSのラッパーの影響大？。画認アプリVaRecogも追加。M7適用済み
   MOD:450msec
   SOD:450msec
   SMP:128msec
   PLR:1000msec

** 今後の予定
*** バス負荷対策。(1stStep,2ndStep)
   1stStep適用で処理時間向上をCL確認
    MOD:530m - 176m
    SOD:108m - 33m
    SMP:153m - 46m
    PLR:594m - 192m
    測定条件：HDMI、トップビュー、MOD、駐車枠、ver37

   1stStep - ソース優位かデスティネーション優位かの変更。7/13週のSIに入れる(塩屋様)
   2ndStep - 内容が理解出来ておらず、具体的な対策内容が盛り込めていない。


*** DL対応 - CL
   初期検討：8月初旬
   検討完了：8月末

*** コンパイルオプション改善
*** DisplayListは   CLで対応可能となってきた
*** 最新ソースコードでのアルゴリズムの最適化検討
   - 最新ソース入手：7/17(金)予定

** CL開発日程
  '15年07月末 RFQ回答(予定)。但しコストで揉めている模様
  '15年11月末 EIPF#2
  '16年06月 VCロット

** 課題リスト
*** 管理表外:ローダータスクの変更方法
   効率よく立ち上げる為に、ローダータスクの優先度を下げたい。
   各タスクのイベント待ち状態への移行を優先としたい。
   - [ ] ADaC : ブートの内容をCLより教えて貰って、効率のいい立ち上げ方を相互検討する
   現状困っているわけではない (川上様)

*** 管理表外:OSのAPI処理時間
   Timed for semapho

*** 管理表外:localmutexの待ちの処理順はTASKの優先度順について
   全部同じ優先度なので処理待ち順だと思う
   現状困っているわけではない (川上様)
   改めて質問事項纏めてからQA表で依頼を行うこととする (川上様)

*** No.18派生 : APIの処理時間開示依頼

** 8月 月例MTG

* 議事録：7/14 GHS来日MTG (記：高田)
** 川上氏：ローダータスクの優先度を変更したい（設定可能にしたい）
  Scott氏：動的に変えることは必要か？
  Startupより低く、LateKernelrangeclearより高い優先度に固定予定です。
  Scott氏：検討する
  起動時に１CPUで動作することにより遅延し、タイムアウトなどのエラーが
  発生することを防ぎたい
  ローダー動作時も機能が不全になることを防ぎたい
  Scott氏：ちゃんとしたインシデントで対応したい

  要望の目的：
  モニタとのネゴがあるので１ｓで起動することを要望されている
  （KT法の準拠のため、車両搭乗＆シフトRから２ｓ以内にリア映像が表示できる必要がある）

  ローダータスクに合わせて他のタスクを優先度上げる選択はあり得ない
  （255,254のため、全タスクをその優先度にすることは現実的でない）

  ７月中に回答をいただく。

** 川上氏：OSのAPIの時間を測定したがTimedWaitForSemaphoが40〜50us
  通常のWaitForSemaphoは13us  時間がかかっている。Scott氏の測定時間と違う
  環境は一次試作機(GHSに渡したものと同じ)、DebugKernel
  起動時？
  1000回の平均値：時間測定､EventAnalyzerで処理内容を確認
  TimedWaitForSemaphoが失敗して時間を食っているのでは？
  Scott氏：Evetlogが欲しい。
      ETRはサポートされていないので別のやり方をして欲しい
  慶野氏：オンサイトで指導します。＞※後でやりとりして調整


** 川上氏：localmutex、優先度順はTASKの優先度順か？
  複数のタスクがmutex待ちした場合、mutexリリース後のWaitタスクの動作順は？
  FIFO？PRIORITY? セマフォは設定できるが、localmutexで設定できるのか？
  Scott氏：複数のタスクが資源取得した場合localmutexとセマフォは同じ時間程度になる。
  川上氏：ニーズを確認の上、必要ならインシデントベースで整理して質問する。


** 川上氏：SPIの処理時間について(QA表No.111)

** 川上氏：QOSの設定について
  設定はルネサスBootloaderにソースで入っている。

  VinのFIFOのオーバフロー対策としてQOS変更が必要
    >対策値を後日送付予定

  U-BootとBootloaderで違っており、
  Bootloaderで動作させた場合、しばらくシステム動作させるとハングアップする。

  ・ルネサス様にBOOTLOADERを送付する（弊社カスタマイズしたもの、QOSの値はそのまま)>@川上氏
    →再現確認をしていただく>@ルネサス様
  ・u-bootにbootloaderの値を設定したもので再現するか評価する>@川上氏
  ・booloaderでの現象を再確認し、整理しておく>@川上氏

  QOSの設定内容についての説明資料を提供していただく>@ルネサス様


** 高田氏：ADaC/GHS提供のドライバの品質の扱いがどうなっているか？
  ADaC：  ASISと契約的になっており、サンプル扱い、使用した場合クラリオンで品質確認の必要あり
    TCPスタックのセットは品質保証対象である。

** 加藤氏：ルネサス様の提供ミドル(CVlib)の品質について
  ルネサス：
    CVLib/IVLibは品質確認作業をしている最中
    テスト内容と、結果を提示した参考資料を最終的に提示する>@ルネサス様

** 岩田氏：OSについての品質について
  ADaC：OS品確資料は別途有償で提供可能 ←見積もりが欲しい >@ADaC様
    BSP品確資料は別途有償で提供可能 ←見積もりが欲しい >@ADaC様
    Q1リリースのISO26262認証資料も別途有償で提供可能(Kernel) ←見積もりが欲しい >@ADaC様
    ISO26262はBSPやドライバも含めた認証のためのサポート資料提供可能

    BSPもASIS(GHSの中では品確している)

MISRA-2004はコンパイラの機能を利用して検証している。
  吉岡：実際に実施したオプションをいただきたい>@ADaC

** 川上氏：Flash/CRCの件を催促
  ADaC：状況をメール報告



** 今後の進め方について（岩田K）
・画認のDLを全部入れるのがいつか？  ８／末を想定
・View Step1&Step2対応が残っている
結果どの程度になる?


  今週SI(Step1投入品)のものを提供する  ルネサス様・ADaC/GHS >@Clarion
  今週SIの画像認識動作時間の指標を提示する。>@Clarion

2018向けの開発も同時に進めており、
画像認識アプリケーションも増えていく
あわよくば2017モデルに投入する顧客意向が有る。

 GHS:Scott様は8月来日しない予定である。


  岩田氏：今後緊急で解決しなければならない問題に備え、
      大塚でリモートでバッグ環境で立ち会い実施する体制を整えて欲しい

** 次回：
  隔週の定例電話会議を実施：7/27 18:00-(19:00?)
  参考：CLの盆休み8/8-16

