* <2015-02-27 金>@ 10:00-12:00 機能安全・セキュリティサポートプログラム説明
** 出席 :: 石倉様、吉岡様、森澤様、？？、下平様、真壁様、川口様、中村様、？？
   REL/砂田さん、鈴木(政)さん、大塚さん、木内さん、西田さん
          REC/高草、藤巻
+ [ ] :: 説明資料


** セキュリティサポート背景説明
*** 背景
2011年にISO26262リリースも思ったより浸透していない。
規格も抽象的でどこまでやればいいのか明確ではない。
2005年からルネサスで対応している知見を生かしてお客様のサポートを行う

欧州からセキュリティに対する要求が来ているが、お客様も規格もない、コモンセンスもないでどうすればいいかわからないと言われる
ルネサスにはICカードビジネルで対応した実績がある。

** ルネサス機能安全取り組み
プレゼン資料にて説明

 - 質問 :: フルで機能安全を盛り込んだ場合、どれくらい性能が落ちるか？ 森澤様
 - 回答 :: ざっくりだが、Maxで約半分だと思ってもらいたい。 木内さん

** サポート内容説明
プレゼン資料参照

** サポートプログラムロードマップ
・E-ラーニング
社内教育用をお客様向けに公開予定
・コンサルの拡充
・MCALドライバの提供やSafeyOSのサポート

k
吉岡様 - CPUコアセルフテストはSafety SW driverに含まれるのか？
砂田さん - 入ります。但し自社製CPU(RH850)のみ
木内さん - R-CarのARMコアは他社(Yogitech)対応でRELでは対応予定なし。
吉岡様 - トータルパッケージとして全てルネサスで診てもらえないのか
木内さん - 今後Yogitechとの打合せにRELも参加するなどはしたい

砂田さん - 機能安全の取り組みは以前にもやったことがあると伺っているが？
吉岡さん - 前回はアセスメントまでいかず、オージットレベルでCL社内対応

砂田さん - Safetyゴールとかはっきりしていますかね？
吉岡様 - はっきりしてないですよね

砂田さん - 要望事項はありますか？
森澤様 - 機能安全に関わる部分は全てやってもらいたいくらいの勢いです

吉岡様 - 暗号化の対応は？
木内さん - 暗号化IPはNDA保護の元で情報開示。マニュアルにも未記載としている。セキュアブートに対応

吉岡様 - CPUコア診断はソフトウェアの介在なしでハードのみとならないのか。
砂田さん - ロックステップデュアルという解はあるが、ARMコアだとそれも難しいよね。

川口様 - (内部に対して)ツールあったほうが開発効率上がるよね？
砂田さん - 現在ツールは使っていますか？
森澤様 - ガイア？さんのツールを使用している

砂田さん - ASILはどこまでやることになっていますか
吉岡様 - 今回のシステムとしてはASIL-D対応予定だが、確定していない。

吉岡様 - CANのASIL-D対応要望がある。対応方法として、ループバック、CRCやカウンタによる整合チェックがあると思っている
砂田さん - ループバックはシステムとして嬉しくないと思う

木内さん - 補足事項。
           V2HはASIL対応外。サポートプログラムも未適用。
           ただ機能安全を意識した設計はしているので、SH77650相当以上は対応出来る。
           RH850＋サポートグラムでV2Hも考慮したサポートをさせて頂くつもりです。

川口様 - V2H + F1L だとASIL-D対応出来ないのではないかと考えており、F1L以外のマイコンを紹介して欲しい
藤巻 - 4月CS対応と言われるとF1L以外の解がない

川口様 - 価格イメージは？
砂田さん - アドバンストパッケージ ＋ 技術サーポート：FMEDAツール/1年 で約1000万円

中村様 - 仕様等Fixしていないが、えんかん2015年12月と言われている。VC:2016/8月
